name: dcli_sdk
version: 4.0.1-alpha.10
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: Dart console SDK - write console (cli) apps/scripts using dart.
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  dcli:
  dcli_common:
  dcli_core:
  dcli_terminal:
  meta: ^1.10.0
  path: ^1.8.3
  pub_semver: ^2.1.4
  pubspec_lock: ^3.0.2
  pubspec_manager: ^1.0.0-alpha.6
  scope: ^4.1.0
  stack_trace: ^1.11.1
  strings: ^3.0.0
  win32: ^4.0.0
 
dev_dependencies:
  test: ^1.24.7
  dcli_test:
executables:
  dcli:
  dcli_complete:
  dcli_install:
platforms:
  linux:
  macos:
  windows:
